# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_id', models.IntegerField(null=True, verbose_name='第三方来源产生的id,e.g:微信')),
                ('third_type', models.IntegerField(null=True, verbose_name='0:未知，1:微信， 2:支付宝')),
                ('mobile', models.CharField(max_length=64, null=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='邮箱')),
                ('user_name', models.CharField(default='看看', max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('level', models.IntegerField(default=0, max_length=64, verbose_name='等级')),
                ('icon_url', models.CharField(default='', max_length=64, verbose_name='头像')),
                ('user_status', models.IntegerField(verbose_name='0：正常 1：冻结')),
                ('sex', models.IntegerField(verbose_name='性别 0：女 1：男 2：保密')),
                ('autograph', models.TextField(max_length=2500, null=True, verbose_name='个性签名')),
                ('birthday', models.CharField(max_length=256, null=True, verbose_name='生日')),
                ('user_create_time', models.DateTimeField(auto_now_add=True, verbose_name='视频创建时间')),
                ('user_update_time', models.DateTimeField(auto_now=True, verbose_name='视频更新时间')),
            ],
        ),
    ]
