# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
    ]
