# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180720_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='autograph',
            field=models.TextField(max_length=2500, null=True, verbose_name=b'\xe4\xb8\xaa\xe6\x80\xa7\xe7\xad\xbe\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=256, null=True, verbose_name=b'\xe7\x94\x9f\xe6\x97\xa5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, null=True, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon_url',
            field=models.CharField(default=b'', max_length=64, verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0, verbose_name=b'\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=64, null=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(verbose_name=b'\xe6\x80\xa7\xe5\x88\xab 0\xef\xbc\x9a\xe5\xa5\xb3 1\xef\xbc\x9a\xe7\x94\xb7 2\xef\xbc\x9a\xe4\xbf\x9d\xe5\xaf\x86'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_id',
            field=models.IntegerField(null=True, verbose_name=b'\xe7\xac\xac\xe4\xb8\x89\xe6\x96\xb9\xe6\x9d\xa5\xe6\xba\x90\xe4\xba\xa7\xe7\x94\x9f\xe7\x9a\x84id,e.g:\xe5\xbe\xae\xe4\xbf\xa1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_type',
            field=models.IntegerField(null=True, verbose_name=b'0:\xe6\x9c\xaa\xe7\x9f\xa5\xef\xbc\x8c1:\xe5\xbe\xae\xe4\xbf\xa1\xef\xbc\x8c 2:\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x9d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=b'\xe7\x9c\x8b\xe7\x9c\x8b', max_length=64, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.IntegerField(verbose_name=b'0\xef\xbc\x9a\xe6\xad\xa3\xe5\xb8\xb8 1\xef\xbc\x9a\xe5\x86\xbb\xe7\xbb\x93'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
