# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_length', models.CharField(default=None, max_length=32, null=True, verbose_name='视频时长')),
                ('video_title', models.CharField(default='', max_length=256, verbose_name='视频标题')),
                ('video_path', models.CharField(default='', max_length=128, verbose_name='视频存取路径')),
                ('video_author', models.CharField(default='', max_length=64, verbose_name='视频作者')),
                ('video_author_id', models.CharField(default='', max_length=64, verbose_name='视频作者id')),
                ('video_author_v_id', models.CharField(max_length=64, null=True, verbose_name='视频作者wx_id,如果是别的来源，则无此id')),
                ('video_channel', models.IntegerField(null=True, verbose_name='视频来源渠道， 1为糗百，2为b站， 3为其他')),
                ('video_create_time', models.DateTimeField(auto_now_add=True, verbose_name='视频创建时间')),
                ('video_update_time', models.DateTimeField(auto_now=True, verbose_name='视频更新时间')),
            ],
        ),
    ]
