# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='video_author',
            field=models.CharField(max_length=64, verbose_name='视频作者'),
        ),
        migrations.AlterField(
            model_name='library',
            name='video_author_id',
            field=models.IntegerField(verbose_name='视频作者id'),
        ),
    ]
