# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20181128_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='actor',
            field=models.TextField(max_length=50000, null=True, verbose_name=b'\xe6\xbc\x94\xe5\x91\x98'),
        ),
    ]
