# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20181129_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='actors',
            field=models.TextField(max_length=50000, null=True, verbose_name=b'\xe6\xbc\x94\xe5\x91\x98\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='actor',
            field=models.CharField(max_length=32, null=True, verbose_name=b'\xe6\xbc\x94\xe5\x91\x98'),
        ),
    ]
