# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20181129_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='record_company',
            field=models.TextField(max_length=50000, null=True, verbose_name=b'\xe5\x88\xb6\xe4\xbd\x9c\xe5\x85\xac\xe5\x8f\xb8'),
        ),
    ]
