# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20181129_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='record_company',
            field=models.TextField(max_length=5000, null=True, verbose_name=b'\xe5\x88\xb6\xe4\xbd\x9c\xe5\x85\xac\xe5\x8f\xb8'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='video_img',
            field=models.CharField(default=None, max_length=256, verbose_name=b'\xe5\xbd\xb1\xe7\x89\x87\xe5\xb0\x81\xe9\x9d\xa2\xe5\x9b\xbe'),
        ),
    ]
