# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20181129_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_piece',
            name='buy_ticket_index',
            field=models.CharField(max_length=32, null=True, verbose_name=b'\xe8\xb4\xad\xe7\xa5\xa8\xe6\x8c\x87\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='row_piece',
            name='rap_index',
            field=models.CharField(max_length=32, null=True, verbose_name=b'\xe5\x8f\xa3\xe7\xa2\x91\xe6\x8c\x87\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='row_piece',
            name='ren_zhi_index',
            field=models.CharField(max_length=32, null=True, verbose_name=b'\xe8\xae\xa4\xe7\x9f\xa5\xe6\x8c\x87\xe6\x95\xb0'),
        ),
    ]
