# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20181129_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='douban_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default=None, max_length=64, verbose_name=b'\xe5\xbd\xb1\xe7\x89\x87\xe5\x90\x8d\xe7\xa7\xb0')),
                ('rate', models.CharField(default=None, max_length=16, null=True, verbose_name=b'\xe5\xbd\xb1\xe7\x89\x87\xe5\x90\x8d\xe7\xa7\xb0')),
                ('director', models.CharField(default=None, max_length=256, verbose_name=b'\xe5\xaf\xbc\xe6\xbc\x94')),
                ('casts', models.CharField(default=None, max_length=256, verbose_name=b'\xe6\xbc\x94\xe5\x91\x98')),
                ('connection_url', models.CharField(default=None, max_length=128, verbose_name=b'\xe8\xb1\x86\xe7\x93\xa3\xe8\xbf\x9e\xe6\x8e\xa5')),
            ],
        ),
    ]
