# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_douban_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='douban_data',
            name='box_office_create_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe9\x87\x87\xe9\x9b\x86\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='douban_data',
            name='data_channel',
            field=models.CharField(default=b'\xe8\x89\xba\xe6\x81\xa9', max_length=32, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x9d\xa5\xe6\xba\x90'),
        ),
    ]
