# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20181130_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouth_word',
            name='box_office_create_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe9\x87\x87\xe9\x9b\x86\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_content',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe7\x9f\xad\xe8\xaf\x84\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_content_lev',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe8\xaf\x84\xe5\x88\x86\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_content_long',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe9\x95\xbf\xe8\xaf\x84\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_content_time',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_num',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe8\xaf\x84\xe5\x88\x86\xe4\xba\xba\xe6\x95\xb0'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_rate',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe8\xa7\x82\xe4\xbc\x97\xe8\xaf\x84\xe5\x88\x86'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='data_channel',
            field=models.CharField(default=b'\xe7\x8c\xab\xe7\x9c\xbc', max_length=32, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x9d\xa5\xe6\xba\x90'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='video_name',
            field=models.CharField(default=None, max_length=64, verbose_name=b'\xe5\xbd\xb1\xe7\x89\x87\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='video_rate',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe5\xbd\xb1\xe7\x89\x87\xe8\xaf\x84\xe5\x88\x86'),
        ),
        migrations.AlterField(
            model_name='douban_data',
            name='data_channel',
            field=models.CharField(default=b'\xe8\x89\xba\xe6\x81\xa9', max_length=32, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x9d\xa5\xe6\xba\x90 `'),
        ),
        migrations.AlterField(
            model_name='douban_data',
            name='rate',
            field=models.CharField(default=None, max_length=16, null=True, verbose_name=b'\xe8\xaf\x84\xe5\x88\x86'),
        ),
    ]
