# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20181201_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouth_word',
            name='cityName',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_id',
            field=models.IntegerField(null=True, verbose_name=b'\xe8\xaf\x84\xe8\xae\xbaid'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='comment_time',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='director',
            field=models.CharField(default=None, max_length=64, verbose_name=b'\xe5\xaf\xbc\xe6\xbc\x94'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='fra',
            field=models.CharField(default=None, max_length=64, verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe5\x9b\xbd\xe5\xae\xb6'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='gender',
            field=models.IntegerField(null=True, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='nickName',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe8\x80\x85\xe5\x90\x8d\xe5\xad\x97'),
        ),
        migrations.AddField(
            model_name='mouth_word',
            name='video_type',
            field=models.CharField(default=None, max_length=256, verbose_name=b'\xe5\xbd\xb1\xe7\x89\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
