# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_auto_20181201_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth_word',
            name='comment_content',
            field=models.TextField(default=None, max_length=64, null=True, verbose_name=b'\xe7\x9f\xad\xe8\xaf\x84\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
