# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_auto_20181201_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth_word',
            name='director',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe5\xaf\xbc\xe6\xbc\x94'),
        ),
        migrations.AlterField(
            model_name='mouth_word',
            name='fra',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe5\x9b\xbd\xe5\xae\xb6'),
        ),
    ]
